on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created

name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: set package.json version
        uses: menduz/oddish-action@master
        working-directory: ./kernel/static
        with:
          deterministic-snapshot: true
          only-update-versions: true

      - name: install
        working-directory: kernel
        run: npm ci
      - name: build
        working-directory: kernel
        run: make build-release build-deploy

      - name: deploy preview
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CDN_BUCKET: ${{ secrets.CDN_BUCKET }}
        run: |
          npx @dcl/cdn-uploader@next \
            --bucket $CDN_BUCKET \
            --local-folder kernel/static \
            --bucket-folder "@dcl/kernel/branch/${{ github.head_ref }}"

      - name: publish package
        uses: menduz/oddish-action@master
        with:
          registry-url: "https://registry.npmjs.org"
          access: public
          cwd: ./kernel/static
          ## use action runId instead of current date to generate snapshot numbers
          deterministic-snapshot: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
