on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created

name: code validations
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: browser-actions/setup-chrome@latest

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"

      - name: install
        working-directory: kernel
        run: npm ci

      - name: test-ci
        working-directory: kernel
        run: make test-ci
        if: ${{ always() }}

      - name: lint
        working-directory: kernel
        run: make lint
        if: ${{ always() }}

      # - name: codecov
      #   working-directory: kernel
      #   run: npx codecov
